// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Xml;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.IO;

namespace RestServer
{
    public class XMLSerializerImpl
    {
        public static string Serialize<T>(T tData)
        {
            var serializer = new XmlSerializer(typeof(T));
            
            TextWriter writer = new StringWriter();
            serializer.Serialize(writer, tData);
            
            return writer.ToString();
        }
        
        public static T Deserialize<T>(string tData)
        {
            
            var serializer = new XmlSerializer(typeof(T));
            
            TextReader reader = new StringReader(tData);
            
            return (T)serializer.Deserialize(reader);
        }


    }
}

